### ISSUE TITLE
Support gpt-4-32k model?

### ISSUE THREAD

**Issue by OneSeven** [tiktoken-go/tokenizer#4]
Now there is no option for gpt-4-32k in the model list 。

**Comment by bluescreen10** [comment]
👋 Hi there,

This follows OpenAI's python tiktoken library very close. The models listed [there](https://github.com/pandodao/tokenizer-go/tree/main/js) does not include a specific version for `gpt-4-32k` I think you should use the plain old `gpt-4` model.

Hope this helps!.
